In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
df = pd.read_csv("C:/Health Analysis/data/diabetes_data.csv")
df

Age  Sex  HighChol  CholCheck   BMI  Smoker  HeartDiseaseorAttack  \
0       4.0  1.0       0.0        1.0  26.0     0.0                   0.0   
1      12.0  1.0       1.0        1.0  26.0     1.0                   0.0   
2      13.0  1.0       0.0        1.0  26.0     0.0                   0.0   
3      11.0  1.0       1.0        1.0  28.0     1.0                   0.0   
4       8.0  0.0       0.0        1.0  29.0     1.0                   0.0   
...     ...  ...       ...        ...   ...     ...                   ...   
70687   6.0  0.0       1.0        1.0  37.0     0.0                   0.0   
70688  10.0  1.0       1.0        1.0  29.0     1.0                   1.0   
70689  13.0  0.0       1.0        1.0  25.0     0.0                   1.0   
70690  11.0  0.0       1.0        1.0  18.0     0.0                   0.0   
70691   9.0  0.0       1.0        1.0  25.0     0.0                   1.0   

       PhysActivity  Fruits  Veggies  HvyAlcoholConsump  GenHlth  MentHlth  \
0               1.0     0.0      1.0                0.0      3.0       5.0   
1               0.0     1.0      0.0                0.0      3.0       0.0   
2               1.0     1.0      1.0                0.0      1.0       0.0   
3               1.0     1.0      1.0                0.0      3.0       0.0   
4               1.0     1.0      1.0                0.0      2.0       0.0   
...             ...     ...      ...                ...      ...       ...   
70687           0.0     0.0      1.0                0.0      4.0       0.0   
70688           0.0     1.0      1.0                0.0      2.0       0.0   
70689           0.0     1.0      0.0                0.0      5.0      15.0   
70690           0.0     0.0      0.0                0.0      4.0       0.0   
70691           1.0     1.0      0.0                0.0      2.0       0.0   

       PhysHlth  DiffWalk  Stroke  HighBP  Diabetes  
0          30.0       0.0     0.0     1.0       0.0  
1           0.0       0.0     1.0     1.0       0.0  
2          10.0       0.0     0.0     0.0       0.0  
3           3.0       0.0     0.0     1.0       0.0  
4           0.0       0.0     0.0     0.0       0.0  
...         ...       ...     ...     ...       ...  
70687       0.0       0.0     0.0     0.0       1.0  
70688       0.0       1.0     0.0     0.0       1.0  
70689       0.0       1.0     0.0     1.0       1.0  
70690       0.0       1.0     0.0     1.0       1.0  
70691       0.0       0.0     0.0     1.0       1.0  

[70692 rows x 18 columns]

In [2]:
# 원핫인코딩
df = pd.get_dummies(df, columns=['Age', 'Sex', 'HighChol', 'CholCheck', 'Smoker',
       'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'GenHlth', 'DiffWalk',
       'Stroke', 'HighBP'])
df

BMI  MentHlth  PhysHlth  Diabetes  Age_1.0  Age_2.0  Age_3.0  Age_4.0  \
0      26.0       5.0      30.0       0.0        0        0        0        1   
1      26.0       0.0       0.0       0.0        0        0        0        0   
2      26.0       0.0      10.0       0.0        0        0        0        0   
3      28.0       0.0       3.0       0.0        0        0        0        0   
4      29.0       0.0       0.0       0.0        0        0        0        0   
...     ...       ...       ...       ...      ...      ...      ...      ...   
70687  37.0       0.0       0.0       1.0        0        0        0        0   
70688  29.0       0.0       0.0       1.0        0        0        0        0   
70689  25.0      15.0       0.0       1.0        0        0        0        0   
70690  18.0       0.0       0.0       1.0        0        0        0        0   
70691  25.0       0.0       0.0       1.0        0        0        0        0   

       Age_5.0  Age_6.0  ...  GenHlth_2.0  GenHlth_3.0  GenHlth_4.0  \
0            0        0  ...            0            1            0   
1            0        0  ...            0            1            0   
2            0        0  ...            0            0            0   
3            0        0  ...            0            1            0   
4            0        0  ...            1            0            0   
...        ...      ...  ...          ...          ...          ...   
70687        0        1  ...            0            0            1   
70688        0        0  ...            1            0            0   
70689        0        0  ...            0            0            0   
70690        0        0  ...            0            0            1   
70691        0        0  ...            1            0            0   

       GenHlth_5.0  DiffWalk_0.0  DiffWalk_1.0  Stroke_0.0  Stroke_1.0  \
0                0             1             0           1           0   
1                0             1             0           0           1   
2                0             1             0           1           0   
3                0             1             0           1           0   
4                0             1             0           1           0   
...            ...           ...           ...         ...         ...   
70687            0             1             0           1           0   
70688            0             0             1           1           0   
70689            1             0             1           1           0   
70690            0             0             1           1           0   
70691            0             1             0           1           0   

       HighBP_0.0  HighBP_1.0  
0               0           1  
1               0           1  
2               1           0  
3               0           1  
4               1           0  
...           ...         ...  
70687           1           0  
70688           1           0  
70689           0           1  
70690           0           1  
70691           0           1  

[70692 rows x 46 columns]

In [3]:
from joblib import load
model = load('C:/Health Analysis/logit.h5')
scaler = load('C:/Health Analysis/scaler.model')

In [4]:
df.columns

Index(['BMI', 'MentHlth', 'PhysHlth', 'Diabetes', 'Age_1.0', 'Age_2.0',
       'Age_3.0', 'Age_4.0', 'Age_5.0', 'Age_6.0', 'Age_7.0', 'Age_8.0',
       'Age_9.0', 'Age_10.0', 'Age_11.0', 'Age_12.0', 'Age_13.0', 'Sex_0.0',
       'Sex_1.0', 'HighChol_0.0', 'HighChol_1.0', 'CholCheck_0.0',
       'CholCheck_1.0', 'Smoker_0.0', 'Smoker_1.0', 'HeartDiseaseorAttack_0.0',
       'HeartDiseaseorAttack_1.0', 'PhysActivity_0.0', 'PhysActivity_1.0',
       'Fruits_0.0', 'Fruits_1.0', 'Veggies_0.0', 'Veggies_1.0',
       'HvyAlcoholConsump_0.0', 'HvyAlcoholConsump_1.0', 'GenHlth_1.0',
       'GenHlth_2.0', 'GenHlth_3.0', 'GenHlth_4.0', 'GenHlth_5.0',
       'DiffWalk_0.0', 'DiffWalk_1.0', 'Stroke_0.0', 'Stroke_1.0',
       'HighBP_0.0', 'HighBP_1.0'],
      dtype='object')

In [5]:
print(df.head(3))

    BMI  MentHlth  PhysHlth  Diabetes  Age_1.0  Age_2.0  Age_3.0  Age_4.0  \
0  26.0       5.0      30.0       0.0        0        0        0        1   
1  26.0       0.0       0.0       0.0        0        0        0        0   
2  26.0       0.0      10.0       0.0        0        0        0        0   

   Age_5.0  Age_6.0  ...  GenHlth_2.0  GenHlth_3.0  GenHlth_4.0  GenHlth_5.0  \
0        0        0  ...            0            1            0            0   
1        0        0  ...            0            1            0            0   
2        0        0  ...            0            0            0            0   

   DiffWalk_0.0  DiffWalk_1.0  Stroke_0.0  Stroke_1.0  HighBP_0.0  HighBP_1.0  
0             1             0           1           0           0           1  
1             1             0           0           1           0           1  
2             1             0           1           0           1           0  

[3 rows x 46 columns]


In [15]:
a = [[26, 5, 30, #BMI, 마음건강, 육체건강
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # 나이대
     1, 0, #성별
     1, 0, #콜레스테롤
     0, 1, #콜레스테롤 검사
     1, 0, #흡연
     1, 0, #심장병
     0, 1, #운동
     0, 1, #과일
     0, 1, #야채
     1, 0, #음주
     0, 1, 0, 0, 0, #전반적인 건강
     1, 0, #걷기 어려움
     1, 0, #뇌졸증
     1, 0]] #고혈압
b = scaler.transform(a)
prob = model.predict_proba(b)
predict = model.predict(b)
print(prob)
predict

[[0.87446935 0.12553065]]


c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0.])

In [17]:
train_cols = [x for x in list(df.columns) if x not in ['Diabetes']]
X = df[train_cols]
y = df['Diabetes']

In [18]:
import numpy as np
idx = np.random.randint(0,len(X)+1,10)
test_set = X.iloc[idx]
y_t = y.iloc[idx]

In [20]:
for i in range(10):
    test_i = [list(test_set.iloc[i].values)]
    test_i = scaler.transform(test_i)
    print(model.predict_proba(test_i))

[[0.09100456 0.90899544]]
[[0.23290344 0.76709656]]
[[0.49763394 0.50236606]]
[[0.86415472 0.13584528]]
[[0.92328999 0.07671001]]
[[0.87823679 0.12176321]]
[[0.72840255 0.27159745]]
[[0.49783073 0.50216927]]
[[0.16083422 0.83916578]]
[[0.73665774 0.26334226]]


c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warning

In [21]:
y_t

66198    1.0
65266    1.0
31890    0.0
18301    0.0
34842    0.0
2043     0.0
22862    0.0
64532    1.0
59895    1.0
6561     0.0
Name: Diabetes, dtype: float64

In [23]:
from keras.models import load_model
neo_model = load_model('C:/Health Analysis/neo_keras.h5')

In [30]:
a = [[26, 5, 30, #BMI, 마음건강, 육체건강
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, # 나이대
     1, 0, #성별
     1, 0, #콜레스테롤
     0, 1, #콜레스테롤 검사
     1, 0, #흡연
     1, 0, #심장병
     0, 1, #운동
     0, 1, #과일
     0, 1, #야채
     1, 0, #음주
     0, 1, 0, 0, 0, #전반적인 건강
     1, 0, #걷기 어려움
     1, 0, #뇌졸증
     1, 0]] #고혈압
b = scaler.transform(a)
prob = neo_model.predict(b)
print(prob)
predict = [1 if prob >= 0.5 else 0]
predict

1/1 [==============================] - 0s 25ms/step
[[0.1286348]]


c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


[0]

In [31]:
import numpy as np
idx = np.random.randint(0,len(X)+1,10)
test_set = X.iloc[idx]
y_t = y.iloc[idx]

In [32]:
for i in range(10):
    test_i = [list(test_set.iloc[i].values)]
    test_i = scaler.transform(test_i)
    print(neo_model.predict(test_i))

1/1 [==============================] - 0s 35ms/step
[[0.5026306]]
1/1 [==============================] - 0s 30ms/step


c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


[[0.61921644]]
1/1 [==============================] - 0s 26ms/step
[[0.03663561]]
1/1 [==============================] - 0s 27ms/step
[[0.6640699]]
1/1 [==============================] - 0s 23ms/step
[[0.49902037]]
1/1 [==============================] - ETA: 0s

c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 20ms/step
[[0.04298999]]
1/1 [==============================] - 0s 22ms/step
[[0.27374125]]
1/1 [==============================] - 0s 21ms/step
[[0.892237]]
1/1 [==============================] - 0s 24ms/step
[[0.1924758]]


c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 22ms/step
[[0.04060506]]


In [33]:
y_t

5133     0.0
39251    1.0
20937    0.0
2531     0.0
29881    0.0
4976     0.0
25754    0.0
52825    1.0
2110     0.0
19689    0.0
Name: Diabetes, dtype: float64